### PR TITLE
Fix non-native field multiplication wraparound soundness regression

### LINKED ISSUE #953: Fix non-native field multiplication wraparound soundness regression

### PR DESCRIPTION
**Pull request by jspada**
Special thanks to @querolita for solving the wraparound instances for the tests!

Closes #953

### CODE REVIEW

File: kimchi/src/tests/foreign_field_mul.rs [hunk 1]
```diff
@@ -927,6 +927,57 @@ fn test_invalid_carry1_hi_plookup() {
...
+    assert!(wraparound_0 - PallasField::one() >= PallasField::from(2u32).pow(&[12u64]));
+    assert!(two_to_9 * (wraparound_0 - PallasField::one()) >= PallasField::from(2u32).pow(&[12u64]));
+    // edge case: x + 8 is not a wraparound value
+    assert!(wraparound_0 + PallasField::from(8) >= PallasField::from(2u32).pow(&[12u64]));
+    assert!(two_to_9 * (wraparound_0 + PallasField::from(8)) >= PallasField::from(2u32).pow(&[12u64]));
+
+    // Invalid carry1_hi witness that causes wrap around to something less than 3-bits
+    let (result, witness) = run_test::<Vesta, VestaBaseSponge, VestaScalarSponge>(
+        true,
+        false, // Disable external checks so we can catch carry1_hi plookup failure
```
Comment (mrmr1993) [inline kimchi/src/tests/foreign_field_mul.rs:955]: No need now, but to make the code self-documenting, we really should either
* make this function call take a record
* create a dedicated enum `CheckConstraints::{WithGateConstraints, WithoutGateConstraints}`

**Review by mrmr1993 — APPROVED** [review]

File: kimchi/src/tests/foreign_field_mul.rs (hunk 1 above)
Comment (jspada) [reply kimchi/src/tests/foreign_field_mul.rs:960]: It would also be good to
* make it only create CS once and then test many witnesses against it
* factor it out so could be used by other tests
