### PR TITLE
o1vm/mips: fix failing constraints

### LINKED ISSUE #2075: Fix MIPS failing constraints
When running the `main.rs` with the generic prover I could observe some MIPS constraints not passing. Figure out why and which and fix it.

### PR DESCRIPTION
**Pull request by marcbeunardeau88**
fixe the remaining failing Mips instr
see : https://github.com/o1-labs/proof-systems/issues/2075
Closes #2075

### CODE REVIEW

**Comment by dannywillems** [comment]
Can you rebase on top of https://github.com/o1-labs/proof-systems/pull/2700 for the CI please?

File: o1vm/src/interpreters/mips/witness.rs [hunk 1]
```diff
@@ -362,12 +362,26 @@ impl<Fp: Field, PreImageOracle: PreImageOracleT> InterpreterEnv for Env<Fp, PreI
...
+            let is_zero: u64 = if to_zero_test == Fp::zero() { 1 } else { 0 };
+            self.write_column(pos, is_zero);
+            is_zero
+        };
+        let _to_zero_test_inv_or_zero = {
+            let pos = self.alloc_scratch();
+            let inv_or_zero = if to_zero_test == Fp::zero() {
+                Fp::zero()
+            } else {
+                Fp::inverse(&to_zero_test).unwrap()
```
Comment (dannywillems) [inline o1vm/src/interpreters/mips/witness.rs:379]: See a direct optimisation available [here](https://github.com/o1-labs/proof-systems/pull/2040)

Comment (querolita) [reply o1vm/src/interpreters/mips/witness.rs:379]: And [here](https://github.com/o1-labs/proof-systems/pull/2047), built on top of that one

File: o1vm/src/interpreters/mips/witness.rs [hunk 2]
```diff
@@ -362,12 +362,26 @@ impl<Fp: Field, PreImageOracle: PreImageOracleT> InterpreterEnv for Env<Fp, PreI
...
+        let to_zero_test = Fp::from(*x) - Fp::from(*y);
+        let res = {
+            let pos = self.alloc_scratch();
+            let is_zero: u64 = if to_zero_test == Fp::zero() { 1 } else { 0 };
+            self.write_column(pos, is_zero);
+            is_zero
+        };
+        let _to_zero_test_inv_or_zero = {
+            let pos = self.alloc_scratch();
+            let inv_or_zero = if to_zero_test == Fp::zero() {
```
Comment (querolita) [inline o1vm/src/interpreters/mips/witness.rs:376]: You can probably call `inverse_or_zero` in these lines, no? I guess the bug comes from the `res` block, there's no need to unroll the `inv_or_zero` to solve the bug.

File: o1vm/src/interpreters/mips/witness.rs [hunk 3]
```diff
@@ -362,12 +362,26 @@ impl<Fp: Field, PreImageOracle: PreImageOracleT> InterpreterEnv for Env<Fp, PreI
     }
 
     fn equal(&mut self, x: &Self::Variable, y: &Self::Variable) -> Self::Variable {
-        // To avoid subtraction overflow in the witness interpreter for u32
-        if x > y {
-            self.is_zero(&(*x - *y))
-        } else {
-            self.is_zero(&(*y - *x))
-        }
+        // We replicate is_zero(x-y), but working on field elt,
```
Comment (querolita) [inline o1vm/src/interpreters/mips/witness.rs:365]: Perhaps it's less error prone if you move the `is_zero()` in `interpreter.rs` into `constraint.rs` and define a variant of `is_zero()` in `witness.rs` containing precisely your replication here in `equal()`. Otherwise, one could call the `is_zero()` from `interpreter.rs` for the witness and incur in the same problem being fixed in this PR.

**Review by querolita — COMMENTED** [review]
I left a few suggestions to help keep the different interpreters separated in scope, I hope it can be useful. Other than that, I will happily approve the PR, as it does not change all of the `Self::Variables` to field, but it keeps it as native type. Either way, I believe that addressing Danny's optimization can be a smart move after the constraints fix is merged. But I would first focus on this PR and work on https://github.com/o1-labs/proof-systems/pull/2040 / and https://github.com/o1-labs/proof-systems/pull/2047 afterwards, because it is a different issue being targeted there.

**Comment by dannywillems** [comment]
@marcbeunardeau88 can you change the target branch to match @shimkiv one please?

File: o1vm/src/interpreters/mips/witness.rs [hunk 4]
```diff
@@ -362,12 +362,26 @@ impl<Fp: Field, PreImageOracle: PreImageOracleT> InterpreterEnv for Env<Fp, PreI
...
+        // to avoid subtraction overflow in the witness interpreter for u32
+        let to_zero_test = Fp::from(*x) - Fp::from(*y);
```
Comment (dannywillems) [inline o1vm/src/interpreters/mips/witness.rs:367]: You don't need to convert as early as here in `Fp`.

File: o1vm/src/interpreters/mips/witness.rs (hunk 2 above)
Comment (marcbeunardeau88) [reply o1vm/src/interpreters/mips/witness.rs:376]: I thought so at first as well, but Inverse_or_zero is forced to return a Variable by the signature, so we can't get the resulting field_inversion we desire here.

File: o1vm/src/interpreters/mips/witness.rs (hunk 4 above)
Comment (marcbeunardeau88) [reply o1vm/src/interpreters/mips/witness.rs:367]: Indeed, but I believe this to be more clear, and the performance is negligibly impacted

**Review by querolita — APPROVED** [review]
Awesome 😄

**Comment by dannywillems** [comment]
Please reopen the PR targetting master, @marcbeunardeau88
